### ISSUE TITLE
[MacOS] bug: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by notiv-nt** [mrmlnc/svg2sprite-cli#4]
## To reproduce:

* Create an empty folder
* `yarn add svg2sprite-cli`
* Add script
	```javascript
	"scripts": {
		"sprite": "svg2sprite"
	},
	```
* Error: `env: node\r: No such file or directory`

## Problem:
![image](https://user-images.githubusercontent.com/10743009/46126488-25066a00-c236-11e8-8df1-1e75b9311fd1.png)

## Solution:
Change line endings to LF

![image](https://user-images.githubusercontent.com/10743009/46126507-3cddee00-c236-11e8-9319-895931569197.png)

**Comment by notiv-nt** [comment]
@mrmlnc

**Comment by mrmlnc** [comment]
Sorry, but I don't fully understand your problem.

How do you run npm script?

**Comment by notiv-nt** [comment]
yarn add svg2sprite-cli
yarn sprite

**Comment by notiv-nt** [comment]
Problem in line endings, must be LF instead of CRLF

**Comment by notiv-nt** [comment]
Switching to the svg-sprite package

**Comment by glebmachine** [comment]
Still got same error(

**Comment by cenda** [comment]
same here, change CRLF -> LF line endings in `node_modules/svg2sprite-cli/out/cli.js` file fixed an issue, but I think that's not a good idea to manually change such thing

**Comment by dimitriy-k** [comment]
yeah, here the same issue on Mac OS

**Comment by notiv-nt** [comment]
Use svg-sprite

```
svg-sprite -s --symbol-sprite='sprite.svg' --symbol-dest=public/assets --shape-id-generator='icon-%s' source/icons/*.svg
```
